version: "3.4"
services:
  webclient:
    build:
      context: .
      dockerfile: src/client/blazor/YetAnotherNoteTaker.Blazor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
    depends_on:
      - webserver
  webserver:
    build:
      context: .
      dockerfile: src/server/YetAnotherNoteTaker.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "5002:27017"