version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: src/server/YetAnotherNoteTaker.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
        - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "5002:27017"