version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: src/server/YetAnotherNoteTaker.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
        - ravendb
  ravendb:
    image: ravendb/ravendb
    volumes:
        - ./ravendb-data:/opt/RavenDB/Server/RavenData
    environment:
        - RAVEN_Setup_Mode=None
        - RAVEN_Licence_Eula_Accepted=true
        - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    ports:
      - "5002:8080"
      - "38888:38888"